Update Mockall to 0.7.0 to fix test failures on recent nightlies
---- common::vdev_block::t::t::issueing_queued stdout ----
thread 'common::vdev_block::t::t::issueing_queued' panicked at 'attempted to leave type `std::mem::ManuallyDrop<std::cell::UnsafeCell<std::boxed::Box<std::boxed::Box<dyn std::ops::FnOnce(divbuf::divbuf::DivBufMut, u64) -> std::boxed::Box<dyn futures::future::Future<Item = (), Error = common::Error>>>>>>` uninitialized, which is invalid', /rustc/f05a5240440b3eaef1684a7965860fab40301947/src/libcore/mem/mod.rs:655:5